import { useSchema, activeSchemaHash, CURRENT_SCHEMA_HASH } from '../../chain/schema.js';
// Replays the shared Degenerette wild-color vectors (generated by
// degenerus-audit/scripts/data/degenerette_wild_vectors.py, verified there
// against the compiled contracts) through the site's reel, scoring, rig,
// payout and event decoders.

import { describe, test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { keccak256, toBeHex, zeroPadValue } from 'ethers';

import {
  dgnOrdinaryLanes, dgnHouseLanes, dgnHouseTraits, dgnPlayerTicket, dgnRollSpin,
  dgnScoreWilds, dgnSpinSymbol, dgnWilds,
} from '../dgn-reels.js';
import { decodeDegeneretteSpins, degenerettePayoutTable, degeneretteSpinPayout } from '../degenerette.js';
import { decodeBoxSpin } from '../lootbox-legs.js';
import { dgnHeroQuadrant, dgnUnpackTicket } from '../dgn-traits.js';

const FIXTURE_URL = new URL('./fixtures/degenerette-wild-vectors.json', import.meta.url);
const FIXTURE_SHA256 = '974dcb9829b08c6a3152fac6b9a0d221f7f836009f1c4ec322ae59399a9bf695';
const raw = readFileSync(FIXTURE_URL);
const vectors = JSON.parse(raw.toString('utf8'));

const RESULT_TICKET_TAG = 0x446567656E526573756C74n;
const word32 = (x) => zeroPadValue(toBeHex(BigInt(x)), 32);
const hash2 = (a, b) => BigInt(keccak256(`${word32(a)}${word32(b).slice(2)}`));
const hash4 = (a, b, c, d) => BigInt(keccak256(
  `${word32(a)}${[b, c, d].map((x) => word32(x).slice(2)).join('')}`,
));
const u32 = (hex) => Number(BigInt(hex));
const CURRENCY_ETH = 0;
const CURRENCY_FLIP = 1;
const CURRENCY_WWXRP = 3;

// Gross payout of one spin at its exact table row (no FLIP whole-token floor).
function rawPayout(currency, stake, activity, score, wilds) {
  const row = degenerettePayoutTable({ currency, activityScore: activity, wilds }).rows[score];
  return (BigInt(stake) * row.multiplierNumerator) / row.multiplierDenominator;
}

describe('degenerette wild-color shared vectors', () => {
  let previous;
  before(() => { previous = activeSchemaHash(); useSchema(CURRENT_SCHEMA_HASH); });
  after(() => useSchema(previous));
  test('the fixture is the audit repo file, byte for byte', () => {
    assert.equal(createHash('sha256').update(raw).digest('hex'), FIXTURE_SHA256);
  });

  test('ordinary and house lane producers', () => {
    for (const p of vectors.producers) {
      assert.equal(dgnOrdinaryLanes(BigInt(p.rand)), u32(p.ordinary));
      assert.equal(dgnHouseLanes(BigInt(p.rand)), u32(p.house));
    }
    const wild = vectors.producers.find((p) => (u32(p.house) & 0x40) !== 0);
    assert.ok(wild, 'the fixture includes a house wild lane');
  });

  test('placed-bet spins: reels, score, wild count, tail byte and payouts', () => {
    for (const v of vectors.bet_spins) {
      const word = BigInt(v.word);
      const seed = hash4(word, v.index, v.symbol, v.spin);
      const symbol = dgnSpinSymbol(seed, v.symbol);
      const player = dgnPlayerTicket(seed, symbol);
      const house = dgnHouseTraits({ rngWord: word, index: v.index, spinIdx: v.spin });
      assert.equal(player, u32(v.player), `player ${v.word}/${v.spin}`);
      assert.equal(house, u32(v.house), `house ${v.word}/${v.spin}`);
      const { score, wilds } = dgnScoreWilds(player, house);
      assert.equal(score, v.score);
      assert.equal(wilds, v.wilds);
      assert.equal(dgnWilds(house), v.wilds);
      assert.equal(dgnHeroQuadrant(player), symbol >> 3);

      // DegeneretteResolved spin entry: 4 big-endian player bytes + tail byte.
      const bytes = [(player >>> 24) & 0xFF, (player >>> 16) & 0xFF, (player >>> 8) & 0xFF, player & 0xFF, v.tail_byte];
      assert.equal(v.tail_byte, score | (wilds << 4));
      const [spin] = decodeDegeneretteSpins(bytes);
      assert.deepEqual(spin, { spinIndex: 0, playerTraits: player, score: v.score, wilds: v.wilds });

      assert.equal(String(degeneretteSpinPayout({
        currency: CURRENCY_ETH, amountPerSpin: BigInt(v.eth_stake_wei), activityScore: v.activity, score, wilds,
      })), v.eth_payout_wei, 'ETH payout');
      assert.equal(String(rawPayout(CURRENCY_FLIP, v.flip_stake, v.activity, score, wilds)),
        v.flip_payout_pre_survival, 'FLIP payout');
    }
  });

  test('box spins: rolled reels, WWXRP rig, payouts and BoxSpin decode', () => {
    const helped = new Set();
    for (const v of vectors.box_spins) {
      const seed = BigInt(v.spin_seed);
      const spin = dgnRollSpin({
        seed, houseSeed: hash2(seed, RESULT_TICKET_TAG), symbol: v.symbol, currency: v.currency,
      });
      assert.equal(spin.hero, v.hero);
      assert.equal(spin.player, u32(v.player));
      assert.equal(spin.naturalHouse, u32(v.natural_house));
      assert.equal(spin.house, u32(v.house));
      assert.equal(spin.helped, v.help_applied);
      assert.equal(spin.score, v.score);
      assert.equal(spin.wilds, v.wilds);
      helped.add(v.help_applied);
      assert.equal(String(rawPayout(v.currency, v.stake, v.activity, v.score, v.wilds)), v.raw_payout);

      const typeCode = v.currency === CURRENCY_WWXRP ? 0n : 2n;
      const betId = (1n << 63n) | (typeCode << 60n) | 1n;
      const packed = BigInt(v.player) | (BigInt(v.house) << 32n) | (BigInt(v.score) << 64n) | (1n << 216n);
      const decoded = decodeBoxSpin(betId, packed);
      const [reel] = decoded.reels;
      assert.equal(reel.heroQuadrant, v.hero >> 3);
      assert.equal(decoded.heroQuadrant, v.hero >> 3);
      assert.equal(reel.wilds, v.wilds);
      assert.equal(reel.score, v.score);
      assert.deepEqual(reel.playerTraits, dgnUnpackTicket(v.player));
      assert.deepEqual(reel.resultTraits, dgnUnpackTicket(v.house));
      assert.equal(reel.playerTraits.filter((lane) => lane.wild).length, 1);
    }
    assert.deepEqual([...helped].sort(), [false, true], 'both rig outcomes are covered');
  });

  test('three-spin FLIP box chain decodes to its own heroes and wild counts', () => {
    const chain = vectors.flip_box_chain;
    chain.spins.forEach((v) => {
      const seed = BigInt(v.spin_seed);
      const spin = dgnRollSpin({
        seed, houseSeed: hash2(seed, RESULT_TICKET_TAG), symbol: 32, currency: CURRENCY_FLIP,
      });
      assert.equal(spin.hero, v.hero);
      assert.equal(spin.player, u32(v.player));
      assert.equal(spin.house, u32(v.house));
      assert.equal(spin.score, v.score);
      assert.equal(spin.wilds, v.wilds);
    });
    const decoded = decodeBoxSpin((1n << 63n) | (1n << 60n) | 1n, BigInt(chain.packed_spins));
    assert.equal(decoded.spinType, 'flip');
    assert.equal(decoded.survived, chain.survived);
    assert.equal(decoded.heroQuadrant, null);
    assert.equal(decoded.reels.length, chain.spins.length);
    decoded.reels.forEach((reel, i) => {
      const v = chain.spins[i];
      assert.equal(reel.heroQuadrant, v.hero >> 3);
      assert.equal(reel.score, v.score);
      assert.equal(reel.wilds, v.wilds);
      assert.equal(reel.playerTicket, BigInt(v.player));
      assert.equal(reel.resultTicket, BigInt(v.house));
    });
  });
});
